# Count every mouse click anywhere in the window (and mark an interaction).
$script:Window.Add_PreviewMouseDown({ $script:ActClicks++; Register-OneLinkInteraction })
$script:Window.Add_PreviewKeyDown({ Register-OneLinkInteraction })

# Grid editors are generated by WPF and are absent from $uiNames. Capture
# committed changes by row/column identity, without retaining the entered value.
$ServerGrid.Add_BeginningEdit({
    param($sender, $e)
    if ($e.Column -isnot [System.Windows.Controls.DataGridBoundColumn]) { return }
    $property = [string]$e.Column.Binding.Path.Path
    if ($property) { $sender.Tag = @{ Row = $e.Row.Item; Property = $property; Before = [string]$e.Row.Item.$property } }
})
$ServerGrid.Add_CellEditEnding({
    param($sender, $e)
    $edit = $sender.Tag
    $sender.Tag = $null
    if (-not $edit -or $e.EditAction -ne [System.Windows.Controls.DataGridEditAction]::Commit) { return }
    if ($e.EditingElement -isnot [System.Windows.Controls.TextBox]) { return }
    $value = [string]$e.EditingElement.Text
    if ($value -eq $edit.Before) { return }
    if ($script:ActCaptureEnabled) {
        [void]$script:ActTouchedFields.Add(('Server:{0}:{1}' -f $edit.Row.GetHashCode(), $edit.Property))
        Register-OneLinkInteraction
        $target = if ($edit.Property -eq 'Host') { $value } else { [string]$edit.Row.Host }
        Complete-OneLinkActivity -Name ('Edit Server ' + $edit.Property) -Target $target
    }
})

# Count a DISTINCT field only when the user actually edits it (keyboard focus is
# within the control) - this ignores programmatic combo/text changes on connect,
# refresh, selection-changed defaults, etc.
$fieldTouch = {
    param($s, $e)
    if ($s -and $s.Name -and $s.IsKeyboardFocusWithin) { [void]$script:ActTouchedFields.Add([string]$s.Name); Register-OneLinkInteraction }
}
foreach ($n in $uiNames) {
    $c = Get-Variable -Name $n -Scope Script -ValueOnly -ErrorAction SilentlyContinue
    if ($null -eq $c) { continue }
    if ($c -is [System.Windows.Controls.TextBox]) { if (-not $c.IsReadOnly) { $c.Add_TextChanged($fieldTouch) } }
    elseif ($c -is [System.Windows.Controls.PasswordBox]) { $c.Add_PasswordChanged($fieldTouch) }
    elseif ($c -is [System.Windows.Controls.ComboBox]) {
        $c.Add_SelectionChanged($fieldTouch)
        $c.AddHandler([System.Windows.Controls.Primitives.TextBoxBase]::TextChangedEvent, [System.Windows.Controls.TextChangedEventHandler]$fieldTouch)
    }
    elseif ($c -is [System.Windows.Controls.Primitives.ToggleButton]) { $c.Add_Click($fieldTouch) }
}

# The checkbox turns capture on/off. Turning it ON starts a fresh segment.
$ChkCaptureMetrics.Add_Click({
    Set-OneLinkRecorderCapture ([bool]$ChkCaptureMetrics.IsChecked)
    Write-OneLinkLog ("Efficiency capture {0}." -f $(if ($script:ActCaptureEnabled) { 'STARTED' } else { 'stopped' })) -Level Info
})

# Live footer HUD: shows time + clicks + fields accumulated since the last activity.
Reset-OneLinkActivitySegment
$script:ActHudTimer = New-Object System.Windows.Threading.DispatcherTimer
$script:ActHudTimer.Interval = [TimeSpan]::FromSeconds(1)
$script:ActHudTimer.Add_Tick({
    if (-not $script:ActCaptureEnabled) { $TxtActivityHud.Text = 'Ready'; return }
    # Live ACTIVE time: accumulated + current gap (only while not idle).
    $idleGap = ((Get-Date) - $script:ActLastInteraction).TotalSeconds
    $live = $script:ActActiveSeconds
    $isIdle = ($idleGap -gt $script:ActIdleThresholdSeconds)
    if (-not $isIdle) { $live += $idleGap }
    $clicks = [math]::Max(0, $script:ActClicks - $script:ActBoundaryClicks)
    $inputs = $script:ActTouchedFields.Count
    $state = if ($isIdle) { 'Idle (paused)' } else { 'Recording' }
    $TxtActivityHud.Text = ("{0}  active {1:00}:{2:00}  |  {3} clicks  |  {4} fields" -f $state, [int]([math]::Floor($live / 60)), [int]($live % 60), $clicks, $inputs)
})
$script:ActHudTimer.Start()

# Metrics tab is hidden until the user opens the efficiency panel from the footer
# diamond (no sign-in - just opens Start/Stop capturing + report).
$TabMetrics.Visibility = 'Collapsed'
$BtnUnlockMetrics.Add_Click({ Show-OneLinkCaptureDialog })

# Choose (and remember) where log files are written. Persists across restarts.
$BtnLogFolder.Add_Click({
    $fbd = New-Object System.Windows.Forms.FolderBrowserDialog
    $fbd.Description = "Choose where $($script:AppName) saves its log files (this is remembered next time)."
    if (-not [string]::IsNullOrWhiteSpace($script:LogDirectory) -and (Test-Path -LiteralPath $script:LogDirectory)) { $fbd.SelectedPath = $script:LogDirectory }
    if ($fbd.ShowDialog() -ne [System.Windows.Forms.DialogResult]::OK) { return }
    $new = $fbd.SelectedPath
    if ([string]::IsNullOrWhiteSpace($new)) { return }
    try {
        if (-not (Test-Path -LiteralPath $new)) { New-Item -ItemType Directory -Path $new -Force | Out-Null }
        # Re-point all three logs (activity/efficiency/metrics) to the new folder.
        $script:LogFile = Initialize-OneLinkLogger -Directory $new -GuiCallback $script:LogCallback
        $script:EfficiencyLogFile = Initialize-OneLinkEfficiencyLog -Directory $new
        $script:MetricsLogFile = Initialize-OneLinkMetricsLog -Directory $new
        $script:LogDirectory = $new
        $saved = Save-OneLinkPref -Name 'LogFolder' -Value $new
        $BtnLogFolder.ToolTip = "Log folder: $new`n(Click to change - $($script:AppName) remembers your choice next time.)"
        Write-OneLinkLog "Log folder changed to: $new$(if (-not $saved) { ' (note: could not save the preference file)' })." -Level Success
        $remembered = if ($saved) { "This location is remembered the next time you open $($script:AppName)." } else { "WARNING: the preference could not be saved, so this may not persist after you close $($script:AppName)." }
        Show-InfoMessage ("Log folder set to:`n$new`n`nLogs, efficiency and metrics files will now be written here.`n$remembered")
    }
    catch {
        Show-ErrorMessage "Could not set the log folder to:`n$new`n`n$($_.Exception.Message)"
    }
})


# Keep the Metrics tab hidden whenever it is not the selected tab, so it only
# appears when explicitly opened from the efficiency panel and disappears from
# the tab strip as soon as the user moves to another tab.
$OperationTabs.Add_SelectionChanged({
    if (-not $TabMetrics.IsSelected) { $TabMetrics.Visibility = [System.Windows.Visibility]::Collapsed }
})

